import Foundation

/// Uses an LLM to correct speaker attribution in a diarized conversation.
/// The LLM uses conversational context to fix cases where the diarizer
/// incorrectly grouped both speakers together.
class SpeakerCorrectionService {
    static let shared = SpeakerCorrectionService()

    private let openAI = OpenAIService.shared

    private let systemPrompt = """
    You are a conversation analysis assistant. You will receive a transcript of a conversation between exactly two people (Speaker 1 and Speaker 2). The transcript was generated by an automatic speaker diarization system that sometimes makes mistakes.

    Your job:
    1. FIX SPEAKER LABELS — ensure each speaker is consistently the same person throughout. If a line is clearly a response to the previous line, it should be from the OTHER speaker.
    2. SPLIT merged utterances — if a single utterance clearly contains dialogue from BOTH speakers (a statement + response, question + answer, or an obvious perspective shift from "I" to "you"), split it into two.
    3. MERGE over-split utterances — if consecutive utterances from different speakers are actually one person continuing their thought (e.g., a short follow-up question like "How about yours?" belongs with the preceding statement from the same speaker), merge them.

    Important guidelines:
    - A short follow-up question at the END of a long statement is usually from the SAME speaker, not a new one (e.g., "I finished my big project. How about yours?" = one speaker)
    - Do NOT split a single speaker's multi-sentence turn into multiple speakers just because it contains different ideas. One person can say several sentences in a row.
    - Only split when there is a CLEAR change in who is talking (shift from first-person to second-person perspective, or a direct reply to what was just said)
    - Each speaker has a consistent voice and point of view — use this to resolve ambiguity
    - If all or nearly all text is attributed to one speaker, redistribute based on conversational flow

    Return the corrected transcript in EXACTLY this JSON format:
    {
      "utterances": [
        {"speaker": 1, "text": "text for this line"},
        {"speaker": 2, "text": "text for this line"}
      ]
    }

    Rules:
    - Use only speaker numbers 1 and 2
    - Do NOT change the text content — only fix which speaker said what and merge/split as needed
    - Preserve the chronological order of ALL text
    - When in doubt about splitting, keep it as one utterance
    - Return ONLY valid JSON, no other text
    """

    /// Correct speaker attribution using GPT-4o.
    /// Returns corrected utterances, or nil if LLM is not configured or fails.
    func correctSpeakerAttribution(utterances: [SpeakerUtterance], sessionId: String? = nil) async -> [SpeakerUtterance]? {
        guard openAI.isConfigured else {
            #if DEBUG
            print("LLM speaker correction skipped: no API key configured")
            #endif
            return nil
        }

        guard !utterances.isEmpty else { return nil }

        // Build the transcript to send to the LLM
        let transcript = utterances.enumerated().map { i, u in
            "[\(i)] \(u.speakerLabel): \(u.text)"
        }.joined(separator: "\n")

        let userMessage = """
        Here is the diarized conversation transcript to correct:

        \(transcript)

        Please correct the speaker assignments and return the result as JSON.
        """

        #if DEBUG
        print("=== LLM SPEAKER CORRECTION ===")
        print("Sending \(utterances.count) utterances to GPT-4o for correction...")
        #endif

        do {
            let response = try await openAI.chatCompletion(
                systemPrompt: systemPrompt,
                userMessage: userMessage,
                model: OpenAIService.model,
                temperature: 0.2,
                sessionId: sessionId
            )

            #if DEBUG
            print("LLM response received (\(response.count) chars)")
            #endif

            // Parse the JSON response
            guard let corrected = parseCorrectedUtterances(response, originalUtterances: utterances) else {
                #if DEBUG
                print("Failed to parse LLM response")
                print("Raw response: \(response.prefix(500))")
                #endif
                return nil
            }

            #if DEBUG
            print("LLM corrected \(corrected.count) utterances:")
            for u in corrected {
                print("  \(u.speakerLabel): \(u.text.prefix(60))...")
            }
            print("=== END LLM SPEAKER CORRECTION ===")
            #endif

            return corrected
        } catch {
            #if DEBUG
            print("LLM speaker correction failed: \(error)")
            #endif
            return nil
        }
    }

    /// Parse the LLM's JSON response into SpeakerUtterances.
    private func parseCorrectedUtterances(_ json: String, originalUtterances: [SpeakerUtterance]) -> [SpeakerUtterance]? {
        // Extract JSON from response (LLM might wrap it in markdown code blocks)
        let cleaned = json
            .replacingOccurrences(of: "```json", with: "")
            .replacingOccurrences(of: "```", with: "")
            .trimmingCharacters(in: .whitespacesAndNewlines)

        guard let data = cleaned.data(using: .utf8) else { return nil }

        struct LLMResponse: Decodable {
            struct Utterance: Decodable {
                let speaker: Int
                let text: String
            }
            let utterances: [Utterance]
        }

        do {
            let parsed = try JSONDecoder().decode(LLMResponse.self, from: data)

            // Use timing from original utterances where possible, distribute evenly otherwise
            let totalStart = originalUtterances.first?.startTime ?? 0
            let totalEnd = originalUtterances.last?.endTime ?? 0
            let totalDuration = totalEnd - totalStart

            return parsed.utterances.enumerated().map { i, u in
                // Try to match timing from original utterances
                let startTime: TimeInterval
                let endTime: TimeInterval

                if i < originalUtterances.count {
                    startTime = originalUtterances[i].startTime
                    endTime = originalUtterances[i].endTime
                } else {
                    // Distribute timing evenly for any extra utterances
                    let fraction = Double(i) / Double(max(parsed.utterances.count, 1))
                    startTime = totalStart + fraction * totalDuration
                    endTime = startTime + totalDuration / Double(max(parsed.utterances.count, 1))
                }

                return SpeakerUtterance(
                    speakerId: "speaker_\(u.speaker - 1)",
                    speakerLabel: u.speaker == 1 ? "🔵" : "🟠",
                    text: u.text,
                    startTime: startTime,
                    endTime: endTime
                )
            }
        } catch {
            #if DEBUG
            print("JSON parsing error: \(error)")
            #endif
            return nil
        }
    }
}
